# Test configuration with recent dates
run:
  name: "test_data_fetch"
  seed: 42
  output_dir: "runs"

data:
  source: "yfinance"
  interval: "1d"
  start_date: "2017-01-01"
  end_date: "2024-01-01"
  refresh: false

universe:
  size: 10
  min_turnover: 10000000.0
  min_price: 10.0
  exclude_symbols: []
  lookback_years: 2

detector:
  name: "gap_z"
  window_range: [20, 60]
  k_low_range: [-1.0, -2.0]
  max_hold: 22
  min_hit_rate: 0.4

walk_forward:
  in_sample_years: 3
  out_sample_years: 1
  holdout_years: 2
  calendar_align: true

execution:
  circuit_guard_pct: 0.10
  fees_bps: 10.0
  slippage_model:
    gap_2pct: 5.0
    gap_5pct: 10.0
    gap_high: 20.0

portfolio:
  max_concurrent: 5
  position_size: 100000.0
  equal_weight: true
  reentry_lockout: true

reporting:
  generate_plots: false
  output_formats: ["json", "markdown", "csv"]
  include_unfilled: true