"""
Shared data structures for the application.
"""
from datetime import date
from typing import Dict, List, Literal

import pandas as pd
from pydantic import BaseModel, Field

from src.config import Config

__all__ = ["Trade", "RunProposals", "RunContext", "RunResult"]


class Trade(BaseModel):
    """Represents a single trade with entry and exit points."""

    symbol: str = Field(..., description="The stock symbol.")
    entry_date: date = Field(..., description="The date of trade entry.")
    exit_date: date = Field(..., description="The date of trade exit.")
    entry_price: float = Field(..., gt=0, description="The price at which the trade was entered.")
    exit_price: float = Field(..., gt=0, description="The price at which the trade was exited.")
    sample_type: Literal["IS", "OOS"] = Field(..., description="In-sample (IS) or Out-of-sample (OOS).")

    class Config:
        frozen = True


class RunContext(BaseModel):
    """Inputs required to run a backtest for a single stock."""

    config: Config
    git_hash: str
    data_hash: str


class RunProposals(BaseModel):
    """Proposals (eg: trades, signals) generated by a backtest for a single stock."""

    signals: pd.DataFrame
    trades: List[Trade]

    class Config:
        arbitrary_types_allowed = True


class RunResult(BaseModel):
    """Final result of a backtest for a single stock."""

    context: RunContext
    proposals: RunProposals
    metrics: Dict[str, float]

    class Config:
        arbitrary_types_allowed = True
